package com.jicg.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("mean", "id", Mean.class);
		arp.addMapping("settings", "id", Settings.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("website_data", "id", WebsiteData.class);
	}
}

