package com.jicg.common.model;

import com.jicg.common.model.base.BaseMean;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mean extends BaseMean<Mean> {
	public static final Mean dao = new Mean().dao();


}
