package com.jicg.common.model;

import com.jicg.common.model.base.BaseSettings;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Settings extends BaseSettings<Settings> {
	public static final Settings dao = new Settings().dao();
}
