package com.jicg.common.model;

import com.jicg.common.model.base.BaseWebsiteData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebsiteData extends BaseWebsiteData<WebsiteData> {
	public static final WebsiteData dao = new WebsiteData().dao();
}
